/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BebopSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface BebopSpinner {
    }
    interface BebopStockFinder {
    }
    interface BebopStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLBebopSideDrawerElement extends Components.BebopSideDrawer, HTMLStencilElement {
    }
    var HTMLBebopSideDrawerElement: {
        prototype: HTMLBebopSideDrawerElement;
        new (): HTMLBebopSideDrawerElement;
    };
    interface HTMLBebopSpinnerElement extends Components.BebopSpinner, HTMLStencilElement {
    }
    var HTMLBebopSpinnerElement: {
        prototype: HTMLBebopSpinnerElement;
        new (): HTMLBebopSpinnerElement;
    };
    interface HTMLBebopStockFinderElement extends Components.BebopStockFinder, HTMLStencilElement {
    }
    var HTMLBebopStockFinderElement: {
        prototype: HTMLBebopStockFinderElement;
        new (): HTMLBebopStockFinderElement;
    };
    interface HTMLBebopStockPriceElement extends Components.BebopStockPrice, HTMLStencilElement {
    }
    var HTMLBebopStockPriceElement: {
        prototype: HTMLBebopStockPriceElement;
        new (): HTMLBebopStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "bebop-side-drawer": HTMLBebopSideDrawerElement;
        "bebop-spinner": HTMLBebopSpinnerElement;
        "bebop-stock-finder": HTMLBebopStockFinderElement;
        "bebop-stock-price": HTMLBebopStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface BebopSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface BebopSpinner {
    }
    interface BebopStockFinder {
        "onBebopSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface BebopStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "bebop-side-drawer": BebopSideDrawer;
        "bebop-spinner": BebopSpinner;
        "bebop-stock-finder": BebopStockFinder;
        "bebop-stock-price": BebopStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bebop-side-drawer": LocalJSX.BebopSideDrawer & JSXBase.HTMLAttributes<HTMLBebopSideDrawerElement>;
            "bebop-spinner": LocalJSX.BebopSpinner & JSXBase.HTMLAttributes<HTMLBebopSpinnerElement>;
            "bebop-stock-finder": LocalJSX.BebopStockFinder & JSXBase.HTMLAttributes<HTMLBebopStockFinderElement>;
            "bebop-stock-price": LocalJSX.BebopStockPrice & JSXBase.HTMLAttributes<HTMLBebopStockPriceElement>;
        }
    }
}
